### ISSUE TITLE
Question: Isn't a proof-of-stake (PoS) blockchain less secure/decentralised than a proof-of-work (PoW)?

### ISSUE THREAD

**Issue by Lukas-Kirchbaumer** [InsideTheSim/ethmerge.com-content#36]
This question is awaiting a community contribution.

This question should be discussed in this issue. Once someone has submitted a PR that answers this question (Or the question has been added as an FAQ with no answer content) it will be linked and feedback for the answer should be given on the appropriate PR.

**Comment by InsideTheSim** [comment]
This question has been added to the front-end UI

**Comment by yulesa** [comment]
I never has done this before so he is my answer when the beacon chain launched. I edited it a little to better fit the question. Also English is not natural for me, so it may contain some mistakes.

No, PoS can be much more secure/decentralized than PoW depending how it is designed.
In PoW blockchains, miners try to solve a puzzle to be entitle to a reward. The first miner to solve the puzzle is able to create some coins from thin air to himself: the block reward. PoW miners invest their money in hash power to be able to solve puzzle more frequently. Miners do that by buying more and the best mining rigs available. This hardware doesn’t do useful computational work for the network, it just draw a winner for the block reward prize. PoW miners are essentially staking their money in hardware equipment to get draw more often and get more return.
Pos got rid of this “hardware equipment” intermediary. You stake your money straight and your voting power is proportional to the amount you staked. One person is randomly selected to propose a block and the others have to sign that the block is correct.
In PoW, if miners act maliciously, they lose the block reward and the operational cost of running the rigs like electricity bills and capital cost. The blockchain is safer the more the malicious player has to lose. That way rig operational cost and the block reward has to be higher as possible in order to the network to be safer. That’s the reason PoW is so wasteful in electricity resources. Also, the network security is drastically reduced if the block rewards is suddenly decreased.
PoS operational cost is very low. Instead, if you act maliciously, aside of losing the rewards (a positive reinforcement), your stake is also burned (a negative reinforcement).
This has three advantages:
First, it better aligns incentives to the participants in the network considering that the stake is now denominated in the network currency.
Second, since you lose your stake acting badly, if you try it be dishonest again, your next attack is less effective because your stake is now lower and so is your voting power.
Third, since bad actors now have a negative reinforcement, participants have less wiliness to be malicious and the network positive reinforcement can be lowered to keep the same level of security. Thus, the network can reduce block rewards even increasing it security.
Also, since operational cost are low, more people can participate in the network consensus. You don't need to be close to mining rig distribution channels or have access to lower electricity cost. All resources to run a node in PoS are more easily available which make more affordable to anyone, thus more decentralized. The beacon chain has today over 100K validators.
PoS bigger disadvantage is its engineering complexity. It relies on new ways of using cryptography, much more network communication and strong randomness assumptions. However, this work is already done in the form of “Eth2 node and validators clients” and a user has only to keep it running, connected and updated. Also, that's why it was safer to do that it in a new chain (the beacon chain), because if anything when wrong, nothing happens to the ETH1 chain. This new chain has been running without issues since its launch in December 2020, is securing millions of ETH and is now considered safe to be merged to Ethereum network.

**Comment by timhc22** [comment]
I learnt a lot from reading that thanks @yulesa, have made a few comments on the PR: https://github.com/InsideTheSim/ethmerge.com-content/pull/43
